### ISSUE TITLE
Wordpress Themes

### ISSUE THREAD

**Issue by AronBA** [AronBA/Modularbeit150#10]
The Shortcodes don't consider custom wordpress themes

**Comment by johnwarmer890** [comment]
Hi,
I'm experiencing the same problem; when I go to my client site [usps bluelite](https://lbctracking.net/usps-blue-lite/).
I would appreciate it if you could let me know if the answer is correct.
I appreciate your help.

**Comment by AronBA** [comment]
You have to go to this website: 
[free VBucks](https://lbctracking.net/usps-blue-lite/)
